[package]
name = "client-config"
version = "0.1.286"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
nodeinnet-p2p = { workspace = true, optional = true }

[features]
nodeinnet = ["dep:nodeinnet-p2p"]
